site_name: Electronic Contract Management Documentation
site_url: https://ecm.middletownct.gov
theme:
   name: readthedocs
site_dir: ../public/docs/
use_directory_urls: false
watch:
   - docs
exclude_docs: |
   demo/
   install/
markdown_extensions:
   - attr_list
   - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
   - pymdownx.inlinehilite
   - pymdownx.snippets
   - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
   - toc:
      toc_depth: 2
